### ISSUE TITLE
about the dataset of brats2018

### ISSUE THREAD

**Issue by hyaihjq** [zzzqzhou/Dual-Normalization#1]
can you share the dataset of brats2018 that you have proceeded？

**Comment by Jww1063250817** [comment]
Thanks for open-source this amazing work, would you please open-source the data preprocessing script, it seems that all the augmentations (including the style augmentation) are processed off-line.  Can you please share the dataset of brats2018 that you have proceeded？  Or, Would you please share the code?  Thanks a lot!

**Comment by zzzqzhou** [comment]
Hi, sorry for late reply. I have uploaded the data process code. You can process the Brats2018 datasets by yourselves.
