### ISSUE TITLE
About test data

### ISSUE THREAD

**Issue by Amos1109** [zzzqzhou/Dual-Normalization#12]
您好！非常感谢您出色的工作。但我在测试您的代码时出现了一些问题。我通过preprocess_func.py从训练集合成其他模态的npz文件作为测试数据，但是在测试的时候出现了错误：RuntimeError: The second supplied array does not contain any binary object. 是我构建测试集的方式有问题吗？还是缺少了什么步骤？最后再次感谢您的工作！

**Comment by Hugo-cheng** [comment]
同样遇到这个问题，希望有解答

**Comment by Hugo-cheng** [comment]
![ClassIn_20240610223141](https://github.com/zzzqzhou/Dual-Normalization/assets/65895569/3399c23d-0a33-4ceb-8b81-beaeffe43b2d)
同样遇到这个问题，希望能有解答
