### ISSUE TITLE
关于BraTS的测试集

### ISSUE THREAD

**Issue by XiudingCai** [zzzqzhou/Dual-Normalization#16]
您好！感谢贵方的令人惊叹的工作，我有一些关于论文中BraTS数据集的疑问。请问训练集和测试集是怎么划分的？测试集中的样本序号的是多少？我们最近在跟进这一工作，还请不吝赐教！

**Comment by zzzqzhou** [comment]
I just upload the train and test split on BraTS following our original setting.
