### ISSUE TITLE
About data preprocessing 

### ISSUE THREAD

**Issue by zqaidwj1314** [zzzqzhou/Dual-Normalization#2]
Thanks for open-source this amazing work, would you please open-source the data preprocessing script, it seems that all the augmentations (including the style augmentation) are processed off-line. Would you please share the code? Thanks a lot

**Comment by guomaotianjie** [comment]
yes, I have same question

**Comment by dongdongtong** [comment]
same question and I also want to know how do you split the dataset as train/valid/test?

**Comment by zhenxing123** [comment]
Thanks for open-source this amazing work, would you please open-source the data preprocessing script, it seems that all the augmentations (including the style augmentation) are processed off-line. Would you please share the code? Thanks a lot

**Comment by zhenxing123** [comment]
> Thanks for open-source this amazing work, would you please open-source the data preprocessing script, it seems that all the augmentations (including the style augmentation) are processed off-line. Would you please share the code? Thanks a lot
Hello, may I ask whether the problem of how to preprocess bratS2018 data set has been solved?

**Comment by JoneColdplay** [comment]
yes, I have same question

**Comment by Jww1063250817** [comment]
Firstly, thanks for open-source this amazing work. However, it seems that all the augmentations (including the style augmentation) are processed off-line. Would you please open-source the data preprocessing  code? Thanks a lot!

**Comment by bhosalems** [comment]
Yes, can we please get more details on how the data is preprocessed please?

**Comment by zzzqzhou** [comment]
Hi, sorry for late reply. I have uploaded the data process code.

**Comment by xiayhh** [comment]
> Thanks for open-source this amazing work, would you please open-source the data preprocessing script, it seems that all the augmentations (including the style augmentation) are processed off-line. Would you please share the code? Thanks a lot

Hello, have you reproduced the results of this paper？

**Comment by xiayhh** [comment]
> > Thanks for open-source this amazing work, would you please open-source the data preprocessing script, it seems that all the augmentations (including the style augmentation) are processed off-line. Would you please share the code? Thanks a lot
> > Hello, may I ask whether the problem of how to preprocess bratS2018 data set has been solved?

Hello, have you reproduced the results of this paper？
