### ISSUE TITLE
About test data

### ISSUE THREAD

**Issue by xiayhh** [zzzqzhou/Dual-Normalization#4]
Hello, thank you for opening the code of this paper. I want to ask you what you have done with the test data, and whether you can give some answers.

**Comment by zzzqzhou** [comment]
Hi, sorry for late reply. The process of test domain data is just normalize intensity values of all test images to [-1.0, 1.0] and split 3D volumes into 2D slices.

**Comment by xiayhh** [comment]
> Hi, sorry for late reply. The process of test domain data is just normalize intensity values of all test images to [-1.0, 1.0] and split 3D volumes into 2D slices.

**Comment by xiayhh** [comment]
> Hi, sorry for late reply. The process of test domain data is just normalize intensity values of all test images to [-1.0, 1.0] and split 3D volumes into 2D slices.
Thanks for your reply, I also want to ask you a question. After I started training several times, the dice coefficients of the two modalities of t1 and t1ce are all below 10, but the dice coefficient of the flair mode can reach about 75. But after I trained a few more times, the dice coefficients of the two modes of t1 and t1ce can reach the results of your paper, but the dice coefficient of flair has dropped to about 1, do you know why this is, I am not questioning you , I just want to know if I did something wrong, hope to get your reply, thank you!

**Comment by zzzqzhou** [comment]
Did you use the test code in test_dn_unet.py to evaluate during model training? In test_dn_unet.py, we set the 'train' mode in BN for better results, but when you test target domain during training, this will change the running means and running variances in BN, which may affect the training process. I suggest you to save checkpoints during training and evaluate on checkpoints, so this will not affect the training model. Or, you just evaluate after finishing training.

**Comment by xiayhh** [comment]
> Did you use the test code in test_dn_unet.py to evaluate during model training? In test_dn_unet.py, we set the 'train' mode in BN for better results, but when you test target domain during training, this will change the running means and running variances in BN, which may affect the training process. I suggest you to save checkpoints during training and evaluate on checkpoints, so this will not affect the training model. Or, you just evaluate after finishing training.

First, use preprocess_func.py to divide t2, then use train_dn_unet.py to train for 50 epochs, and finally use test_dn_unet.py on final_model.pth to test the other three modes such as t1. This should be the complete step.  I do it this way.
